[mongodb]
path = "localhost:27017"
dbname = "research"
collections = [ "chart", "dashboard", "database", "dataset", "transtable" ]

[[chart]]
name = "filter_box"
type = "filter_box"
dataset_id = "62cff27c6d81ae2bb7b864b3"
exportable = true

[[chart.inputs]]
name = "平台"
label = "平台"
type = "MultiSelect"
default_value = "allplatid"
required = false

[chart.inputs.source]
type = "URL"

[[chart.inputs.source.value]]
value = "http://dev-game-gm-api.kingnet.com/game/enum/my/platform"

[chart.inputs.default_option]
label = "全部"
value = "allplatid"

[[chart.inputs]]
name = "渠道"
label = "渠道"
type = "MultiSelect"
default_value = "allchannel"
required = false

[chart.inputs.source]
type = "URL"

[[chart.inputs.source.value]]
value = "http://dev-game-gm-api.kingnet.com/game/enum/channel"

[chart.inputs.default_option]
label = "全部"
value = "allchannel"

[[chart.inputs]]
name = "区服"
label = "区服"
type = "MultiSelect"
default_value = "allsid"
required = false

[chart.inputs.source]
type = "URL"

[[chart.inputs.source.value]]
value = "http://dev-game-gm-api.kingnet.com/game/enum/server?state=4"

[chart.inputs.default_option]
label = "全部"
value = "allsid"

[[chart.inputs]]
name = "是否滚服"
label = "是否滚服"
type = "Select"
default_value = "all_gf"
required = false

[chart.inputs.source]
type = "Raw"

[[chart.inputs.source.value]]
label = "是"
value = "1"

[[chart.inputs.source.value]]
label = "否"
value = "0"

[chart.inputs.default_option]
label = "全部"
value = "all_gf"

[[chart.inputs]]
name = "日期"
label = "日期"
type = "RangePicker"
default_value = "6 days from now"
required = true

[[chart]]
name = "基础运营数据"
type = "table"
dataset_id = "62cff27c6d81ae2bb7b864b3"
columns = [
    "日期",
    "平台",
    "渠道",
    "区服",
    "活跃设备数",
    "活跃账号数",
    "活跃角色数",
    "充值账号数",
    "充值金额",
    "充值次数",
    "ARPU",
    "ARPPU",
    "活跃付费率",
    "新增设备数",
    "新增选服账号数",
    "新增账号数",
    "新增创角率",
    "新增角色数",
    "新增充值账号数",
    "新增充值金额",
    "新增充值次数",
    "新增ARPU",
    "新增ARPPU",
    "新增付费率",
    "新付费用户数",
    "新付费用户充值金额"
]
exportable = true

[[chart.orderby]]
column = "日期"
type = "DESC"

[[dashboard]]
app_id = 2
name = "基础运营数据"
charts_ids = [ "62cff27c6d81ae2bb7b864b4", "62cff27c6d81ae2bb7b864b5" ]
sortby = 27

[[dashboard]]
app_id = 2
name = "开服数据"
charts_ids = [ "62cff27c6d81ae2bb7b864b8", "62cff27c6d81ae2bb7b864b9" ]
sortby = 28

[[database]]
db_name = "kingnet_data"
username = "root"
password = "fivekingnet"
host = "172.16.32.243"
port = 3_306
driver = "mysql"
label = "传奇打金"

[[database]]
db_name = "project_2_appid_399"
username = ""
password = ""
host = "192.168.100.10"
port = 8_123
driver = "clickhouse"
label = "传奇打金事件日志"

[[dataSet]]
query = """
SELECT
fds as '日期',
platid as '平台',
channel as '渠道',
sid as '区服',
gf_flag as '是否滚服',
active_did_cnt as '活跃设备数',
active_user_cnt as '活跃账号数',
active_role_cnt as '活跃角色数',
payuser_cnt as '充值账号数',
paysum as '充值金额',
paycnt as '充值次数',
CONVERT((paysum/active_user_cnt),DECIMAL(12,2)) as 'ARPU',
CONVERT((paysum/payuser_cnt),DECIMAL(12,2)) as 'ARPPU',
CONCAT(CONVERT((payuser_cnt/active_user_cnt)*100,DECIMAL(12,2)),'%') as '活跃付费率',
new_did_cnt as '新增设备数',
new_entersid_user_cnt as '新增选服账号数',
new_user_cnt as '新增账号数',
CONCAT(CONVERT((new_user_cnt/new_entersid_user_cnt)*100,DECIMAL(12,2)),'%') as '新增创角率',
new_role_cnt as '新增角色数',
new_user_payuser_cnt as '新增充值账号数',
new_user_paysum as '新增充值金额',
new_user_paycnt as '新增充值次数',
CONVERT((new_user_paysum/new_user_cnt),DECIMAL(12,2)) as '新增ARPU',
CONVERT((new_user_paysum/new_user_payuser_cnt),DECIMAL(12,2)) as '新增ARPPU',
CONCAT(CONVERT((new_user_payuser_cnt/new_user_cnt)*100,DECIMAL(12,2)),'%') as '新增付费率',
new_pay_user_cnt as '新付费用户数',
new_pay_sum as '新付费用户充值金额'
FROM
csys_basic_data_2016002"""
database_id = "62cff27c6d81ae2bb7b864b1"

[[dataSet.columns]]
name = "开合服日期"
label = "开合服日期"

[[dataSet.columns]]
name = "开合服天数"
label = "开合服天数"

[[dataSet.columns]]
name = "区服"
label = "区服"

[dataSet.columns.transtable]
app_id = 2
type = "server"

[[dataSet.columns]]
name = "区服简称"
label = "区服简称"

[[dataSet.columns]]
name = "合服次数"
label = "合服次数"

[[dataSet.columns]]
name = "新增选服账号数"
label = "新增选服账号数"

[[dataSet.columns]]
name = "新增账号数"
label = "新增账号数"

[[dataSet.columns]]
name = "新增创角率"
label = "新增创角率"

[[dataSet.columns]]
name = "活跃账号数"
label = "活跃账号数"

[[dataSet.columns]]
name = "充值金额"
label = "充值金额"

[[dataSet.columns]]
name = "充值账号数"
label = "充值账号数"

[[dataSet.columns]]
name = "充值次数"
label = "充值次数"

[[dataSet.columns]]
name = "ARPU"
label = "ARPU"

[[dataSet.columns]]
name = "ARPPU"
label = "ARPPU"

[[dataSet.columns]]
name = "活跃付费率"
label = "活跃付费率"

[[dataSet.columns]]
name = "新增充值金额"
label = "新增充值金额"

[[dataSet.columns]]
name = "新增充值账号数"
label = "新增充值账号数"

[[dataSet.columns]]
name = "累计新增选服账号数"
label = "累计新增选服账号数"

[[dataSet.columns]]
name = "累计新增账号数"
label = "累计新增账号数"

[[dataSet.columns]]
name = "累计充值账号数"
label = "累计充值账号数"

[[dataSet.columns]]
name = "累计充值金额"
label = "累计充值金额"

[[dataSet.columns]]
name = "累计充值笔数"
label = "累计充值笔数"

[[dataSet.columns]]
name = "累计ARPU"
label = "累计ARPU"

[[dataSet.columns]]
name = "累计ARPPU"
label = "累计ARPPU"

[[dataSet.columns]]
name = "累计付费率"
label = "累计付费率"

[[transtable]]
app_id = 2
type = "platform"
key = "allplatid"
value = "全部"

[[transtable]]
app_id = 2
type = "platform"
key = "1"
value = "传奇打金(1)"
