mongodb:
  path: 'localhost:27017'
  dbname: 'research'
  collections:
    - 'chart'
    - 'dashboard'
    - 'database'
    - 'dataset'
    - 'transtable'

chart:
    - name: filter_box
      type: filter_box
      dataset_id: 62cff27c6d81ae2bb7b864b3
      inputs:
        - name: 平台
          label: 平台
          type: MultiSelect
          source:
            type: URL
            value: 'http://dev-game-gm-api.kingnet.com/game/enum/my/platform'
          default_option:
            label: 全部
            value: allplatid
          default_value: allplatid
          required: false
        - name: 渠道
          label: 渠道
          type: MultiSelect
          source:
            type: URL
            value: 'http://dev-game-gm-api.kingnet.com/game/enum/channel'
          default_option:
            label: 全部
            value: allchannel
          default_value: allchannel
          required: false
        - name: 区服
          label: 区服
          type: MultiSelect
          source:
            type: URL
            value: 'http://dev-game-gm-api.kingnet.com/game/enum/server?state=4'
          default_option:
            label: 全部
            value: allsid
          default_value: allsid
          required: false
        - name: 是否滚服
          label: 是否滚服
          type: Select
          source:
            type: Raw
            value:
              - label: 是
                value: '1'
              - label: 否
                value: '0'
          default_option:
            label: 全部
            value: all_gf
          default_value: all_gf
          required: false
        - name: 日期
          label: 日期
          type: RangePicker
          default_value: 6 days from now
          required: true
      exportable: true
    - name: 基础运营数据
      type: table
      dataset_id: 62cff27c6d81ae2bb7b864b3
      columns:
        - 日期
        - 平台
        - 渠道
        - 区服
        - 活跃设备数
        - 活跃账号数
        - 活跃角色数
        - 充值账号数
        - 充值金额
        - 充值次数
        - ARPU
        - ARPPU
        - 活跃付费率
        - 新增设备数
        - 新增选服账号数
        - 新增账号数
        - 新增创角率
        - 新增角色数
        - 新增充值账号数
        - 新增充值金额
        - 新增充值次数
        - 新增ARPU
        - 新增ARPPU
        - 新增付费率
        - 新付费用户数
        - 新付费用户充值金额
      orderby:
        - column: 日期
          type: DESC
      exportable: true

dashboard:
    - app_id: 2
      name: 基础运营数据
      charts_ids:
        - 62cff27c6d81ae2bb7b864b4
        - 62cff27c6d81ae2bb7b864b5
      sortby: 27
    - app_id: 2
      name: 开服数据
      charts_ids:
        - 62cff27c6d81ae2bb7b864b8
        - 62cff27c6d81ae2bb7b864b9
      sortby: 28

database:
    - db_name: kingnet_data
      username: root
      password: fivekingnet
      host: 172.16.32.243
      port: 3306
      driver: mysql
      label: 传奇打金
    - db_name: project_2_appid_399
      username: ''
      password: ''
      host: 192.168.100.10
      port: 8123
      driver: clickhouse
      label: 传奇打金事件日志

dataSet:
- query: "SELECT\nfds as '日期',\nplatid as '平台',\nchannel as '渠道',\nsid as '区服',\ngf_flag as '是否滚服',\nactive_did_cnt as '活跃设备数',\nactive_user_cnt as '活跃账号数',\nactive_role_cnt as '活跃角色数',\npayuser_cnt as '充值账号数',\npaysum as '充值金额',\npaycnt as '充值次数',\nCONVERT((paysum/active_user_cnt),DECIMAL(12,2)) as 'ARPU',\nCONVERT((paysum/payuser_cnt),DECIMAL(12,2)) as 'ARPPU',\nCONCAT(CONVERT((payuser_cnt/active_user_cnt)*100,DECIMAL(12,2)),'%') as '活跃付费率',\nnew_did_cnt as '新增设备数',\nnew_entersid_user_cnt as '新增选服账号数',\nnew_user_cnt as '新增账号数',\nCONCAT(CONVERT((new_user_cnt/new_entersid_user_cnt)*100,DECIMAL(12,2)),'%') as '新增创角率',\nnew_role_cnt as '新增角色数',\nnew_user_payuser_cnt as '新增充值账号数',\nnew_user_paysum as '新增充值金额',\nnew_user_paycnt as '新增充值次数',\nCONVERT((new_user_paysum/new_user_cnt),DECIMAL(12,2)) as '新增ARPU',\nCONVERT((new_user_paysum/new_user_payuser_cnt),DECIMAL(12,2)) as '新增ARPPU',\nCONCAT(CONVERT((new_user_payuser_cnt/new_user_cnt)*100,DECIMAL(12,2)),'%') as '新增付费率',\nnew_pay_user_cnt as '新付费用户数',\nnew_pay_sum as '新付费用户充值金额'\nFROM\ncsys_basic_data_2016002"
  columns:
    - name: 开合服日期
      label: 开合服日期
    - name: 开合服天数
      label: 开合服天数
    - name: 区服
      label: 区服
      transtable:
        app_id: 2
        type: server
    - name: 区服简称
      label: 区服简称
    - name: 合服次数
      label: 合服次数
    - name: 新增选服账号数
      label: 新增选服账号数
    - name: 新增账号数
      label: 新增账号数
    - name: 新增创角率
      label: 新增创角率
    - name: 活跃账号数
      label: 活跃账号数
    - name: 充值金额
      label: 充值金额
    - name: 充值账号数
      label: 充值账号数
    - name: 充值次数
      label: 充值次数
    - name: ARPU
      label: ARPU
    - name: ARPPU
      label: ARPPU
    - name: 活跃付费率
      label: 活跃付费率
    - name: 新增充值金额
      label: 新增充值金额
    - name: 新增充值账号数
      label: 新增充值账号数
    - name: 累计新增选服账号数
      label: 累计新增选服账号数
    - name: 累计新增账号数
      label: 累计新增账号数
    - name: 累计充值账号数
      label: 累计充值账号数
    - name: 累计充值金额
      label: 累计充值金额
    - name: 累计充值笔数
      label: 累计充值笔数
    - name: 累计ARPU
      label: 累计ARPU
    - name: 累计ARPPU
      label: 累计ARPPU
    - name: 累计付费率
      label: 累计付费率
  database_id: 62cff27c6d81ae2bb7b864b1

transtable:
    - app_id: 2
      type: platform
      key: allplatid
      value: 全部
    - app_id: 2
      type: platform
      key: '1'
      value: 传奇打金(1)

